### ISSUE TITLE
Gdzie umieścić logikę obsługi bazy danych

### ISSUE THREAD

**Issue by CKTA00** [CZOLGOWUS/Nokia-PK-2022#2]
Sposób pierwszy:

Przekazywać do userPort referencje do SMSDB, logika obsługi bazy danych jest w userPort

Sposób drugi:

Niech ConnectedState implementuje publiczny interfejs używany przez userPort do obsługi bazy danych (nie ma bezpośrednio dostępu do funkcji bazy danych, connectedState przechowuje logikę)

**Comment by JarKolod** [comment]
sposób trzeci:

UserPort zwróci odpowiedni identyfikator w co user klikną i dany 'State' wywoła odpowiednie funkcje
